apiVersion: v1
kind: Namespace
metadata:
  name: fleet-recall
  labels:
    fleet-recall.dev/phase: namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: ory
  labels:
    fleet-recall.dev/phase: namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: localstack
  labels:
    fleet-recall.dev/phase: namespaces
