-- no-transaction
-- W2-VIS. Per-row visibility class, enforced INSIDE the recall queries, plus
-- the publication-plane projection the public reader role reads through.
--
-- This migration is ADDITIVE. It creates one new table, appends one column to
-- each of migration 0021's two recall tiers, adds one equality-prefixed vector
-- index, and creates two publication-plane views. It creates no role, installs
-- no grant, and changes no existing column.
--
-- WHY A CLASS PER ROW. A body reaches the recall projection through an accepted
-- evidence event, and that event already carries the server-derived governance
-- envelope: `visibility_class`, `publication_class`, and the protection domain
-- the governed content belongs to. Migration 0019's `memory_body_objects_v1`
-- keeps the protection domain but not the two classes, and content-addressed
-- bodies are shared, so the decision cannot be re-derived from a body row alone.
-- `memory_body_visibility_v1` records it once per body, and the projectors copy
-- it onto every row they write.
--
-- FAIL CLOSED BY CONSTRUCTION, in three independent layers:
--   1. `visibility_class` on both projection tiers DEFAULTS to 'private', so an
--      INSERT that forgets the column, or a row written before this migration,
--      is private -- never publication-safe by omission.
--   2. `memory_body_visibility_publication_requires_approval` makes the
--      database itself refuse a 'publication_safe' row whose recorded evidence
--      classes are not the exact approved pair. A runtime bug cannot store an
--      approval the evidence never granted (PUBLIC-04).
--   3. The publication plane reads only the two views below. A view in
--      CockroachDB executes with its owner's privileges, so the public reader
--      needs -- and is given -- no privilege at all on the base tables. It has
--      no SQL path to a private row: not through a query, not through a count,
--      not through an offset probe.
--
-- C-SPANN EQUALITY PREFIX (migration 0001). The ANN portion of a vector scan is
-- servable only when every column ahead of the vector column is bound with
-- equality. The private plane keeps using
-- `memory_body_dense_projection_semantic_idx` (tenant_id, project, embedding).
-- The publication plane binds a third equality column, so it gets its own index
-- with `visibility_class` in the prefix rather than a post-filter that could
-- truncate an ANN top-k.
--
-- Ownership mirrors migrations 0018-0022: created and owned by fleet_migrator.
-- The publication-role grant is a deployment action, not a migration action;
-- its exact statements are generated by
-- `ostk_fleet_recall::projectors::publication_plane_grant_statements` and are
-- proved end to end by tests/visibility_live.rs.
--
-- CockroachDB 26.2 online DDL: every object is created with IF NOT EXISTS so a
-- process death between a committed schema change and SQLx's history row is
-- resumable, and this migration is registered no_tx and runs in the third
-- (online) execution phase, exactly like migrations 0015 through 0022. Every
-- name is part of the schema contract.

-- One visibility decision per content-addressed body, written by the body
-- projector in the SAME transaction as the body row it describes.
--
-- `source_visibility_class` and `source_publication_class` are the accepted
-- evidence event's own classes, stored verbatim so the derived
-- `visibility_class` is auditable against its input rather than being an
-- opaque verdict.
CREATE TABLE IF NOT EXISTS memory_body_visibility_v1 (
    tenant_id                 UUID NOT NULL,
    project                   STRING NOT NULL,
    body_content_id           BYTES NOT NULL,
    visibility_class          STRING NOT NULL,
    protection_domain_id      STRING NOT NULL,
    source_visibility_class   STRING NOT NULL,
    source_publication_class  STRING NOT NULL,
    first_accepted_event_id   BYTES NOT NULL,
    updated_at                TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (tenant_id, project, body_content_id),
    CONSTRAINT memory_body_visibility_project_bound
        CHECK (octet_length(project) BETWEEN 1 AND 256),
    CONSTRAINT memory_body_visibility_body_shape
        CHECK (octet_length(body_content_id) = 32),
    CONSTRAINT memory_body_visibility_class
        CHECK (visibility_class IN ('private', 'publication_safe')),
    CONSTRAINT memory_body_visibility_domain_bound
        CHECK (octet_length(protection_domain_id) BETWEEN 1 AND 128),
    CONSTRAINT memory_body_visibility_source_visibility
        CHECK (source_visibility_class
               IN ('private', 'project', 'publication_approved')),
    CONSTRAINT memory_body_visibility_source_publication
        CHECK (source_publication_class
               IN ('denied', 'private_only', 'publication_approved')),
    -- The structural half of PUBLIC-04: 'publication_safe' is reachable only
    -- from the exact approved pair of evidence classes.
    CONSTRAINT memory_body_visibility_publication_requires_approval
        CHECK (visibility_class = 'private'
               OR (source_visibility_class = 'publication_approved'
                   AND source_publication_class = 'publication_approved')),
    CONSTRAINT memory_body_visibility_event_shape
        CHECK (octet_length(first_accepted_event_id) = 32)
);

-- Both recall tiers carry the class on the row itself, so the recall predicate
-- is a column comparison in the WHERE clause rather than a join the query
-- planner could reorder after ranking.
ALTER TABLE memory_body_lexical_projection_v1
    ADD COLUMN IF NOT EXISTS visibility_class STRING NOT NULL DEFAULT 'private';
ALTER TABLE memory_body_lexical_projection_v1
    ADD CONSTRAINT IF NOT EXISTS memory_lexical_projection_visibility
        CHECK (visibility_class IN ('private', 'publication_safe'));

ALTER TABLE memory_body_dense_projection_v1
    ADD COLUMN IF NOT EXISTS visibility_class STRING NOT NULL DEFAULT 'private';
ALTER TABLE memory_body_dense_projection_v1
    ADD CONSTRAINT IF NOT EXISTS memory_dense_projection_visibility
        CHECK (visibility_class IN ('private', 'publication_safe'));

-- Publication-plane C-SPANN prefix: (tenant_id, project, visibility_class) are
-- the only columns ahead of `embedding`, and the publication dense query binds
-- all three with equality.
CREATE VECTOR INDEX IF NOT EXISTS memory_body_dense_projection_publication_idx
    ON memory_body_dense_projection_v1
    (tenant_id, project, visibility_class, embedding vector_cosine_ops);

COMMIT;

-- The publication plane's entire surface. Each view is a fixed filtered
-- projection: there is no parameter, no policy row, and no session setting that
-- can widen it, and neither view exposes the class column itself.
CREATE VIEW IF NOT EXISTS memory_body_lexical_publication_v1 AS
    SELECT tenant_id, project, body_content_id, body_created_at, lexical_state,
           unindexable_reason, normalization_version, lexical_text,
           lexical_text_digest, search_document
    FROM public.memory_body_lexical_projection_v1
    WHERE visibility_class = 'publication_safe';

CREATE VIEW IF NOT EXISTS memory_body_dense_publication_v1 AS
    SELECT tenant_id, project, body_content_id, body_created_at,
           embedding_identity_id, model_digest, tokenization_version,
           preprocessing_version, distance_metric, dimensions, embedding
    FROM public.memory_body_dense_projection_v1
    WHERE visibility_class = 'publication_safe';

COMMIT;

-- Fail closed on same-name drift, mirroring migrations 0018, 0019 and 0021:
-- IF NOT EXISTS alone would ADOPT an unrelated object that merely shares a
-- name. Assert the exact column shape of every relation this migration creates
-- or extends; stop on 55000 if a named object is not the object defined here.
DO $$
DECLARE
    drifted STRING;
BEGIN
    SELECT string_agg(expected.relation_name, ', ' ORDER BY expected.relation_name)
    INTO drifted
    FROM (VALUES
        ('memory_body_visibility_v1',
            'tenant_id:uuid:NO,project:text:NO,body_content_id:bytea:NO,visibility_class:text:NO,protection_domain_id:text:NO,source_visibility_class:text:NO,source_publication_class:text:NO,first_accepted_event_id:bytea:NO,updated_at:timestamp with time zone:NO'),
        ('memory_body_lexical_projection_v1',
            'tenant_id:uuid:NO,project:text:NO,body_content_id:bytea:NO,body_created_at:timestamp with time zone:NO,lexical_state:text:NO,unindexable_reason:text:NO,normalization_version:bigint:NO,lexical_text:text:NO,lexical_text_digest:bytea:NO,search_document:tsvector:YES,visibility_class:text:NO'),
        ('memory_body_dense_projection_v1',
            'tenant_id:uuid:NO,project:text:NO,body_content_id:bytea:NO,body_created_at:timestamp with time zone:NO,embedding_identity_id:bytea:NO,model_digest:bytea:NO,tokenization_version:bigint:NO,preprocessing_version:bigint:NO,distance_metric:text:NO,dimensions:bigint:NO,embedding:vector:NO,visibility_class:text:NO'),
        -- A view's columns are always reported nullable by
        -- information_schema, whatever the base column says.
        ('memory_body_lexical_publication_v1',
            'tenant_id:uuid:YES,project:text:YES,body_content_id:bytea:YES,body_created_at:timestamp with time zone:YES,lexical_state:text:YES,unindexable_reason:text:YES,normalization_version:bigint:YES,lexical_text:text:YES,lexical_text_digest:bytea:YES,search_document:tsvector:YES'),
        ('memory_body_dense_publication_v1',
            'tenant_id:uuid:YES,project:text:YES,body_content_id:bytea:YES,body_created_at:timestamp with time zone:YES,embedding_identity_id:bytea:YES,model_digest:bytea:YES,tokenization_version:bigint:YES,preprocessing_version:bigint:YES,distance_metric:text:YES,dimensions:bigint:YES,embedding:vector:YES')
    ) AS expected (relation_name, column_shape)
    WHERE expected.column_shape IS DISTINCT FROM (
        SELECT string_agg(
            column_object.column_name || ':' || column_object.data_type
                || ':' || column_object.is_nullable,
            ','
            ORDER BY column_object.ordinal_position
        )
        FROM information_schema.columns AS column_object
        WHERE column_object.table_schema = 'public'
          AND column_object.table_name = expected.relation_name
    );

    IF drifted IS NOT NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'migration 0023 same-name relation drift: ' || drifted;
    END IF;
END
$$;

-- A view whose column shape matched but whose predicate did not would be a
-- silent publication leak, so assert the predicate itself. Both views must
-- still restrict to the publication-safe class.
DO $$
DECLARE
    unrestricted STRING;
BEGIN
    SELECT string_agg(view_object.table_name, ', ' ORDER BY view_object.table_name)
    INTO unrestricted
    FROM information_schema.views AS view_object
    WHERE view_object.table_schema = 'public'
      AND view_object.table_name IN (
          'memory_body_lexical_publication_v1',
          'memory_body_dense_publication_v1'
      )
      AND view_object.view_definition NOT LIKE '%publication_safe%';

    IF unrestricted IS NOT NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'migration 0023 publication view lost its visibility predicate: '
                || unrestricted;
    END IF;
END
$$;
