apiVersion: 1
datasources:
  - name: Fleet Prometheus
    uid: fleet-prometheus
    type: prometheus
    access: proxy
    url: $FLEET_PROMETHEUS_URL
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
  - name: Fleet Loki
    uid: fleet-loki
    type: loki
    access: proxy
    url: $FLEET_LOKI_URL
    editable: false
    jsonData:
      maxLines: 1000
