use std::collections::{BTreeSet, HashSet};
use std::fs::File;
use std::io::{self, BufRead, BufReader, Read};
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use anyhow::{Context as _, ensure};
use async_trait::async_trait;
use axum::extract::rejection::JsonRejection;
use axum::extract::{DefaultBodyLimit, Request as AxumRequest, State};
use axum::http::{HeaderValue, StatusCode, header};
use axum::middleware::{self, Next};
use axum::response::{Html, IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use chrono::{DateTime, Utc};
use clap::{Parser, Subcommand};
use ostk_fleet_recall::config::model_bundle_sha256;
use ostk_fleet_recall::ledger::CockroachClaimLedger;
use ostk_fleet_recall::mcp::McpServer;
use ostk_fleet_recall::reference_agent::{ReferenceAgentStep, run_reference_agent};
use ostk_fleet_recall::service::{
    FleetMemoryService, RecallAction, RecallRequest, RecallResult, ServiceError,
};
use ostk_fleet_recall::store::cockroach::{
    CockroachStore, EMBEDDING_DIMENSION, PoolConfig, RetryPolicy, ScopedChunk,
    active_embedding_model,
};
use ostk_fleet_recall::{CockroachMemoryService, FleetConfig, FleetScope};
use ostk_recall_core::{
    Chunk, ChunkEmbedder, FacetSet, Links, Source, compose_header, filter_to_allowlist,
    is_archive_parent, is_valid_facet_key,
};
use ostk_recall_embed::Embedder;
use serde::Deserialize;
use serde_json::{Map, Value, json};

const DEFAULT_SOURCE_CONFIG_ID: &str = "fleet:ndjson:v1";
const EMBED_BATCH_SIZE: usize = 64;
const MAX_INGEST_RECORDS: usize = 10_000;
const MAX_NDJSON_LINE_BYTES: usize = 1024 * 1024;
const MAX_TOTAL_INPUT_BYTES: usize = 64 * 1024 * 1024;
const MAX_TEXT_BYTES: usize = 256 * 1024;
// CockroachDB TSVECTOR lexemes are limited to 16,383 bytes. Reject a
// whitespace-delimited input token at a round, conservative UTF-8 byte cap so
// parser normalization cannot turn an otherwise valid import into a DB error.
const MAX_TSVECTOR_INPUT_LEXEME_BYTES: usize = 16_000;
const COCKROACH_TSVECTOR_LEXEME_BYTES: usize = 16_383;
const MAX_SOURCE_ID_BYTES: usize = 4096;
const MAX_SOURCE_CONFIG_ID_BYTES: usize = 256;
const MAX_LINK_ID_BYTES: usize = 4096;
const MAX_PARENT_LINKS: usize = 128;
const MAX_FACET_KEYS: usize = 128;
const MAX_FACET_VALUES_PER_KEY: usize = 64;
const MAX_FACET_KEY_BYTES: usize = 64;
const MAX_FACET_VALUE_BYTES: usize = 4096;
const MAX_DEMO_BODY_BYTES: usize = 16 * 1024;
const MAX_DEMO_QUERY_BYTES: usize = 2_000;
const MAX_DEMO_RESULTS: usize = 20;
const MAX_DEMO_RESPONSE_BYTES: usize = 512 * 1024;
const DEMO_DEADLINE: Duration = Duration::from_secs(15);
const DEMO_HEALTH_CACHE_TTL: Duration = Duration::from_secs(15);
const DEMO_STATUS_CACHE_TTL: Duration = Duration::from_secs(30);
const DEMO_STATUS_RATE_BURST: u32 = 12;
const DEMO_STATUS_RATE_REFILL: Duration = Duration::from_secs(1);
const DEMO_RECALL_RATE_BURST: u32 = 6;
const DEMO_RECALL_RATE_REFILL: Duration = Duration::from_secs(5);

const DEPLOYMENT_CONTROLLED_INGEST_KEYS: &[&str] = &[
    "tenant",
    "tenant_id",
    "project",
    "agent",
    "session",
    "session_id",
    "scope",
    "privacy",
    "privacy_tier",
];

// These fields are generated by the claim projection and transcript
// projection pipelines. Accepting them from operator NDJSON could make an
// ordinary corpus row masquerade as an internal claim/conflict association or
// as a derived transcript row.
const INTERNAL_PROJECTION_INGEST_KEYS: &[&str] = &[
    "claim_id",
    "claim_key",
    "conflict_id",
    "conflict_ids",
    "transcript_projection",
    "projection_version",
    "archive_parent_id",
    "section_index",
    "section_count",
    "previous_section_id",
    "reply_to_chunk_id",
    "embedding_context",
];

#[derive(Debug, Parser)]
#[command(name = "ostk-fleet-recall", version, about)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

struct PinnedEmbedder {
    inner: Embedder,
    identity: String,
}

impl ChunkEmbedder for PinnedEmbedder {
    fn dim(&self) -> usize {
        self.inner.dim()
    }

    fn model_id(&self) -> &str {
        &self.identity
    }

    fn encode_batch(&self, texts: &[&str]) -> Vec<Vec<f32>> {
        self.inner.encode_batch(texts)
    }
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Serve the Recall MCP protocol over stdin/stdout.
    Serve,
    /// Serve the bounded, read-only hackathon demo over HTTP.
    Demo {
        /// Address on which the HTTP demo listens.
        #[arg(long, default_value = "0.0.0.0:8080", value_name = "ADDRESS")]
        listen: SocketAddr,
    },
    /// Apply embedded `CockroachDB` schema migrations.
    Migrate,
    /// Check database connectivity and required capabilities.
    Health,
    /// Upsert trusted, project-scoped chunks from an NDJSON file or stdin.
    Ingest {
        /// NDJSON path, or `-` for stdin.
        #[arg(long, default_value = "-", value_name = "PATH")]
        input: String,
    },
    /// Run one bounded, deterministic policy-agent step against fleet memory.
    ReferenceAgent {
        /// Scenario step. Each step requires its documented deployment-bound agent.
        #[arg(long, value_enum)]
        step: ReferenceAgentStep,
        /// Stable scenario coordinate shared across the selected scenario steps.
        #[arg(long, value_name = "ID")]
        run_id: String,
    },
    /// Print the versioned SHA-256 for a local model2vec bundle.
    ModelDigest {
        /// Directory containing config.json, model.safetensors, and tokenizer.json.
        #[arg(value_name = "BUNDLE")]
        bundle: PathBuf,
    },
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct IngestRecord {
    source: Source,
    source_id: String,
    text: String,
    #[serde(default = "default_source_config_id")]
    source_config_id: String,
    #[serde(default)]
    chunk_index: u32,
    #[serde(default)]
    ts: Option<DateTime<Utc>>,
    #[serde(default)]
    role: Option<IngestRole>,
    #[serde(default)]
    links: Links,
    #[serde(default)]
    facets: FacetSet,
    #[serde(default = "empty_object")]
    extra: Value,
}

#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum IngestRole {
    Primary,
    Evolution,
    Usage,
}

impl IngestRole {
    const fn as_str(self) -> &'static str {
        match self {
            Self::Primary => "primary",
            Self::Evolution => "evolution",
            Self::Usage => "usage",
        }
    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "ostk_fleet_recall=info".into()),
        )
        .with_writer(std::io::stderr)
        .init();

    let cli = Cli::parse();
    if let Command::ModelDigest { ref bundle } = cli.command {
        println!("{}", model_bundle_sha256(bundle)?);
        return Ok(());
    }

    let config = FleetConfig::from_env()?;
    match cli.command {
        Command::Migrate => run_migrate(&config).await?,
        Command::Health => run_health(&config).await?,
        Command::Serve => run_serve(config).await?,
        Command::Demo { listen } => run_demo(config, listen).await?,
        Command::Ingest { input } => run_ingest(&config, &input).await?,
        Command::ReferenceAgent { step, run_id } => {
            run_reference_agent_step(&config, step, &run_id).await?;
        }
        Command::ModelDigest { .. } => unreachable!("handled without deployment configuration"),
    }
    Ok(())
}

async fn run_reference_agent_step(
    config: &FleetConfig,
    step: ReferenceAgentStep,
    run_id: &str,
) -> anyhow::Result<()> {
    let (service, _) = build_memory_service(config).await?;
    let evidence =
        run_reference_agent(service.as_ref(), config.default_scope.clone(), step, run_id)
            .await
            .map_err(anyhow::Error::msg)?;
    println!("{}", serde_json::to_string(&evidence)?);
    Ok(())
}

async fn connect_store(config: &FleetConfig) -> anyhow::Result<CockroachStore> {
    let pool_config = PoolConfig {
        max_connections: config.max_connections,
        ..PoolConfig::default()
    };
    CockroachStore::connect(
        &config.database_url,
        config.default_scope.clone(),
        pool_config,
    )
    .await
    .map_err(Into::into)
}

async fn run_migrate(config: &FleetConfig) -> anyhow::Result<()> {
    let model_identity = validated_migration_model_identity(config)?;
    let store = connect_store(config).await?;
    store.migrate().await?;
    store.initialize_embedding_model(&model_identity).await?;
    let capabilities = store.capabilities().await?;
    println!("{}", serde_json::to_string_pretty(&capabilities)?);
    Ok(())
}

/// Fully load and probe the model before migration can register its immutable
/// corpus identity. A matching bundle hash alone does not prove that the files
/// form a usable 512-dimension model2vec bundle.
fn validated_migration_model_identity(config: &FleetConfig) -> anyhow::Result<String> {
    let embedder = load_pinned_embedder(config)?;
    let model_identity = config.embedding_model_identity();
    ensure!(
        embedder.model_id() == model_identity,
        "validated migration embedder identity does not match configured registry identity"
    );
    Ok(model_identity)
}

async fn run_health(config: &FleetConfig) -> anyhow::Result<()> {
    config.verify_embedding_model_bundle()?;
    let store = connect_store(config).await?;
    store.health_check().await?;
    let expected_model = config.embedding_model_identity();
    let active_model = active_embedding_model(store.pool(), &config.default_scope)
        .await?
        .ok_or_else(|| {
            anyhow::anyhow!(
                "active embedding generation is not initialized; run ostk-fleet-recall migrate"
            )
        })?;
    ensure!(
        active_model == expected_model,
        "configured embedding model {expected_model:?} does not match active corpus model {active_model:?}"
    );
    let capabilities = store.capabilities().await?;
    println!("{}", serde_json::to_string_pretty(&capabilities)?);
    Ok(())
}

async fn run_serve(config: FleetConfig) -> anyhow::Result<()> {
    let (service, _) = build_memory_service(&config).await?;
    McpServer::new(service, config.default_scope)?
        .run_stdio()
        .await?;
    Ok(())
}

async fn build_memory_service(
    config: &FleetConfig,
) -> anyhow::Result<(Arc<CockroachMemoryService>, Arc<CockroachStore>)> {
    let embedder: Arc<dyn ChunkEmbedder> = Arc::new(load_pinned_embedder(config)?);
    let store = Arc::new(connect_store(config).await?);
    store.health_check().await?;
    let ledger = Arc::new(CockroachClaimLedger::new(
        store.pool().clone(),
        config.default_scope.clone(),
        embedder.clone(),
        RetryPolicy::default(),
    )?);
    let service = Arc::new(CockroachMemoryService::new(
        config.default_scope.clone(),
        store.clone(),
        ledger,
        embedder,
    )?);
    service.verify_embedding_generation().await?;
    Ok((service, store))
}

#[derive(Clone)]
struct DemoState {
    service: Arc<dyn FleetMemoryService>,
    health: Arc<dyn DemoHealth>,
    scope: FleetScope,
    capacity: Arc<tokio::sync::Semaphore>,
    health_capacity: Arc<tokio::sync::Semaphore>,
    rate_limits: Arc<DemoRateLimits>,
    health_cache: Arc<DemoHealthCache>,
    status_cache: Arc<DemoStatusCache>,
    clock: Arc<dyn DemoClock>,
}

trait DemoClock: Send + Sync {
    fn now(&self) -> tokio::time::Instant;
}

struct SystemDemoClock;

impl DemoClock for SystemDemoClock {
    fn now(&self) -> tokio::time::Instant {
        tokio::time::Instant::now()
    }
}

#[derive(Clone, Copy)]
struct DemoRatePolicy {
    burst: u32,
    refill_interval: Duration,
}

struct DemoRateLimits {
    status: DemoTokenBucket,
    recall: DemoTokenBucket,
}

impl DemoRateLimits {
    fn new(now: tokio::time::Instant) -> Self {
        Self::with_policies(
            now,
            DemoRatePolicy {
                burst: DEMO_STATUS_RATE_BURST,
                refill_interval: DEMO_STATUS_RATE_REFILL,
            },
            DemoRatePolicy {
                burst: DEMO_RECALL_RATE_BURST,
                refill_interval: DEMO_RECALL_RATE_REFILL,
            },
        )
    }

    fn with_policies(
        now: tokio::time::Instant,
        status: DemoRatePolicy,
        recall: DemoRatePolicy,
    ) -> Self {
        Self {
            status: DemoTokenBucket::new(status, now),
            recall: DemoTokenBucket::new(recall, now),
        }
    }
}

struct DemoTokenBucket {
    capacity: f64,
    refill_interval: Duration,
    state: std::sync::Mutex<DemoTokenBucketState>,
}

struct DemoTokenBucketState {
    tokens: f64,
    last_refill: tokio::time::Instant,
}

impl DemoTokenBucket {
    fn new(policy: DemoRatePolicy, now: tokio::time::Instant) -> Self {
        assert!(policy.burst > 0, "demo rate-limit burst must be positive");
        assert!(
            !policy.refill_interval.is_zero(),
            "demo rate-limit refill interval must be positive"
        );
        let capacity = f64::from(policy.burst);
        Self {
            capacity,
            refill_interval: policy.refill_interval,
            state: std::sync::Mutex::new(DemoTokenBucketState {
                tokens: capacity,
                last_refill: now,
            }),
        }
    }

    fn try_acquire(&self, now: tokio::time::Instant) -> Result<(), Duration> {
        let mut state = self
            .state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        let elapsed = now.saturating_duration_since(state.last_refill);
        let replenished = elapsed.as_secs_f64() / self.refill_interval.as_secs_f64();
        state.tokens = (state.tokens + replenished).min(self.capacity);
        state.last_refill = now;
        if state.tokens >= 1.0 {
            state.tokens -= 1.0;
            Ok(())
        } else {
            Err(self.refill_interval.mul_f64(1.0 - state.tokens))
        }
    }
}

struct DemoStatusCache {
    ttl: Duration,
    entry: std::sync::Mutex<Option<CachedDemoStatus>>,
    refresh: tokio::sync::Semaphore,
}

struct DemoHealthCache {
    ttl: Duration,
    ready_until: std::sync::Mutex<Option<tokio::time::Instant>>,
    refresh: tokio::sync::Semaphore,
}

impl DemoHealthCache {
    fn new(ttl: Duration) -> Self {
        assert!(!ttl.is_zero(), "demo health cache TTL must be positive");
        Self {
            ttl,
            ready_until: std::sync::Mutex::new(None),
            refresh: tokio::sync::Semaphore::new(1),
        }
    }

    fn ready(&self, now: tokio::time::Instant) -> bool {
        let mut ready_until = self
            .ready_until
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        if ready_until.is_some_and(|expires_at| expires_at > now) {
            true
        } else {
            *ready_until = None;
            false
        }
    }

    fn store_ready(&self, now: tokio::time::Instant) {
        let mut ready_until = self
            .ready_until
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        *ready_until = Some(now + self.ttl);
    }
}

impl DemoStatusCache {
    fn new(ttl: Duration) -> Self {
        assert!(!ttl.is_zero(), "demo status cache TTL must be positive");
        Self {
            ttl,
            entry: std::sync::Mutex::new(None),
            refresh: tokio::sync::Semaphore::new(1),
        }
    }

    fn get(&self, now: tokio::time::Instant) -> Option<Arc<Value>> {
        let mut entry = self
            .entry
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        if entry.as_ref().is_some_and(|cached| cached.expires_at > now) {
            entry.as_ref().map(|cached| cached.value.clone())
        } else {
            *entry = None;
            None
        }
    }

    fn store(&self, now: tokio::time::Instant, value: Value) {
        let mut entry = self
            .entry
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        *entry = Some(CachedDemoStatus {
            expires_at: now + self.ttl,
            value: Arc::new(value),
        });
    }
}

struct CachedDemoStatus {
    expires_at: tokio::time::Instant,
    value: Arc<Value>,
}

#[async_trait]
trait DemoHealth: Send + Sync {
    async fn ready(&self) -> Result<(), ()>;
}

#[async_trait]
impl DemoHealth for CockroachStore {
    async fn ready(&self) -> Result<(), ()> {
        self.health_check().await.map_err(|error| {
            tracing::error!(error = %error, "demo readiness check failed");
        })
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct DemoRecallInput {
    query: String,
    #[serde(default)]
    source: Option<String>,
    #[serde(default = "default_demo_limit")]
    limit: usize,
}

const fn default_demo_limit() -> usize {
    8
}

async fn run_demo(config: FleetConfig, listen: SocketAddr) -> anyhow::Result<()> {
    let (service, store) = build_memory_service(&config).await?;
    let clock: Arc<dyn DemoClock> = Arc::new(SystemDemoClock);
    let state = DemoState {
        service,
        health: store,
        scope: config.default_scope,
        capacity: Arc::new(tokio::sync::Semaphore::new(16)),
        // ALB and ECS can probe concurrently. Keep readiness isolated from
        // public API capacity while bounding overlapping database checks.
        health_capacity: Arc::new(tokio::sync::Semaphore::new(2)),
        rate_limits: Arc::new(DemoRateLimits::new(clock.now())),
        health_cache: Arc::new(DemoHealthCache::new(DEMO_HEALTH_CACHE_TTL)),
        status_cache: Arc::new(DemoStatusCache::new(DEMO_STATUS_CACHE_TTL)),
        clock,
    };
    let listener = tokio::net::TcpListener::bind(listen)
        .await
        .with_context(|| format!("bind HTTP demo to {listen}"))?;
    tracing::info!(address = %listener.local_addr()?, "fleet recall demo listening");
    axum::serve(listener, demo_router(state))
        .with_graceful_shutdown(shutdown_signal())
        .await
        .context("serve HTTP demo")?;
    Ok(())
}

fn demo_router(state: DemoState) -> Router {
    let api = Router::new()
        .route(
            "/status",
            get(demo_status).route_layer(middleware::from_fn_with_state(
                state.clone(),
                demo_status_rate_limit,
            )),
        )
        .route(
            "/recall",
            post(demo_recall).route_layer(middleware::from_fn_with_state(
                state.clone(),
                demo_recall_rate_limit,
            )),
        )
        .fallback(demo_api_not_found)
        .method_not_allowed_fallback(demo_api_method_not_allowed);
    Router::new()
        .route("/", get(demo_index))
        .route("/healthz", get(demo_health))
        .nest("/api", api)
        .layer(DefaultBodyLimit::max(MAX_DEMO_BODY_BYTES))
        .with_state(state)
}

async fn shutdown_signal() {
    let interrupt = async {
        tokio::signal::ctrl_c()
            .await
            .expect("install Ctrl-C shutdown handler");
    };
    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("install SIGTERM shutdown handler")
            .recv()
            .await;
    };
    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();
    tokio::select! {
        () = interrupt => {},
        () = terminate => {},
    }
}

async fn demo_index() -> Response {
    let mut response = Html(include_str!("demo.html")).into_response();
    response.headers_mut().insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(
            "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",
        ),
    );
    response.headers_mut().insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    response
}

async fn demo_health(State(state): State<DemoState>) -> Response {
    // Health probes are not rate limited: ALB/ECS liveness must not be able to
    // throttle itself. A short success-only single-flight cache instead bounds
    // database checks while keeping failures immediately observable.
    if state.health_cache.ready(state.clock.now()) {
        return demo_json(StatusCode::OK, json!({ "status": "ready" }));
    }
    let Ok(_refresh) = state.health_cache.refresh.try_acquire() else {
        return demo_json(
            StatusCode::SERVICE_UNAVAILABLE,
            json!({ "status": "unavailable", "reason": "readiness check in progress" }),
        );
    };
    // A refresh may have completed between the first cache check and taking
    // the non-waiting gate.
    if state.health_cache.ready(state.clock.now()) {
        return demo_json(StatusCode::OK, json!({ "status": "ready" }));
    }
    let Ok(_permit) = state.health_capacity.clone().try_acquire_owned() else {
        return demo_json(
            StatusCode::SERVICE_UNAVAILABLE,
            json!({ "status": "unavailable", "reason": "demo is busy; retry shortly" }),
        );
    };
    match tokio::time::timeout(Duration::from_secs(5), state.health.ready()).await {
        Ok(Ok(())) => {
            state.health_cache.store_ready(state.clock.now());
            demo_json(StatusCode::OK, json!({ "status": "ready" }))
        }
        Ok(Err(())) | Err(_) => demo_json(
            StatusCode::SERVICE_UNAVAILABLE,
            json!({ "status": "unavailable" }),
        ),
    }
}

async fn demo_status_rate_limit(
    State(state): State<DemoState>,
    request: AxumRequest,
    next: Next,
) -> Response {
    if let Err(retry_after) = state.rate_limits.status.try_acquire(state.clock.now()) {
        return demo_too_many_requests("request rate limit exceeded; retry shortly", retry_after);
    }
    next.run(request).await
}

async fn demo_recall_rate_limit(
    State(state): State<DemoState>,
    request: AxumRequest,
    next: Next,
) -> Response {
    if let Err(retry_after) = state.rate_limits.recall.try_acquire(state.clock.now()) {
        return demo_too_many_requests("request rate limit exceeded; retry shortly", retry_after);
    }
    next.run(request).await
}

async fn demo_status(State(state): State<DemoState>) -> Response {
    let started = std::time::Instant::now();
    let (response, metric) = cached_demo_status(&state).await;
    with_demo_server_timing(response, started, metric)
}

async fn cached_demo_status(state: &DemoState) -> (Response, &'static str) {
    if let Some(value) = state.status_cache.get(state.clock.now()) {
        return (
            demo_json(StatusCode::OK, value.as_ref().clone()),
            "fleet-recall-cache",
        );
    }
    let Ok(_refresh) = state.status_cache.refresh.try_acquire() else {
        return (
            demo_too_many_requests(
                "status refresh is in progress; retry shortly",
                Duration::from_secs(1),
            ),
            "fleet-recall-overload",
        );
    };
    // A refresh may have completed between the first cache check and taking
    // the non-waiting gate.
    if let Some(value) = state.status_cache.get(state.clock.now()) {
        return (
            demo_json(StatusCode::OK, value.as_ref().clone()),
            "fleet-recall-cache",
        );
    }

    let response = match execute_demo_recall(state, RecallAction::Status, Map::new()).await {
        Ok(result) => bounded_demo_value(result).map_or_else(demo_response_too_large, |value| {
            state.status_cache.store(state.clock.now(), value.clone());
            demo_json(StatusCode::OK, value)
        }),
        Err(response) => response,
    };
    (response, "fleet-recall")
}

async fn demo_recall(
    State(state): State<DemoState>,
    input: Result<Json<DemoRecallInput>, JsonRejection>,
) -> Response {
    let Json(input) = match input {
        Ok(input) => input,
        Err(rejection) => return demo_json_rejection(&rejection),
    };
    if input.query.trim().is_empty()
        || input.query != input.query.trim()
        || input.query.len() > MAX_DEMO_QUERY_BYTES
        || !(1..=MAX_DEMO_RESULTS).contains(&input.limit)
        || input
            .source
            .as_ref()
            .is_some_and(|source| source.trim().is_empty() || source.len() > 256)
    {
        return demo_json(
            StatusCode::BAD_REQUEST,
            json!({
                "error": "query must be trimmed and 1-2,000 bytes; limit must be 1-20; source must be 1-256 bytes"
            }),
        );
    }
    let mut arguments = Map::from_iter([
        ("query".into(), Value::String(input.query)),
        ("limit".into(), json!(input.limit)),
        // Public cards should show distinct source coordinates rather than
        // three neighboring chunks from one long document.
        ("max_per_source_id".into(), json!(1)),
    ]);
    if let Some(source) = input.source {
        arguments.insert("source".into(), Value::String(source));
    }
    dispatch_demo_recall(state, RecallAction::Search, arguments).await
}

async fn demo_api_not_found() -> Response {
    demo_json(
        StatusCode::NOT_FOUND,
        json!({ "error": "API route not found" }),
    )
}

async fn demo_api_method_not_allowed() -> Response {
    demo_json(
        StatusCode::METHOD_NOT_ALLOWED,
        json!({ "error": "method not allowed" }),
    )
}

fn demo_json_rejection(rejection: &JsonRejection) -> Response {
    let status = rejection.status();
    let message = match status {
        StatusCode::PAYLOAD_TOO_LARGE => "request body is too large",
        StatusCode::UNSUPPORTED_MEDIA_TYPE => "content-type must be application/json",
        StatusCode::UNPROCESSABLE_ENTITY => "request JSON does not match the expected shape",
        StatusCode::BAD_REQUEST => "request body must contain valid JSON",
        _ => {
            tracing::warn!(%status, "demo request body extraction failed");
            "request body could not be read"
        }
    };
    demo_json(status, json!({ "error": message }))
}

async fn dispatch_demo_recall(
    state: DemoState,
    action: RecallAction,
    arguments: Map<String, Value>,
) -> Response {
    let started = std::time::Instant::now();
    let response = match execute_demo_recall(&state, action, arguments).await {
        Ok(result) => bounded_demo_response(result),
        Err(response) => response,
    };
    with_demo_server_timing(response, started, "fleet-recall")
}

async fn execute_demo_recall(
    state: &DemoState,
    action: RecallAction,
    arguments: Map<String, Value>,
) -> Result<RecallResult, Response> {
    let Ok(_permit) = state.capacity.clone().try_acquire_owned() else {
        return Err(demo_too_many_requests(
            "demo is busy; retry shortly",
            Duration::from_secs(1),
        ));
    };
    let request = RecallRequest::new(action, arguments);
    match tokio::time::timeout(
        DEMO_DEADLINE,
        state.service.recall(state.scope.clone(), request),
    )
    .await
    {
        Ok(Ok(result)) => Ok(result),
        Ok(Err(ServiceError::InvalidRequest(message))) => Err(demo_json(
            StatusCode::BAD_REQUEST,
            json!({ "error": message }),
        )),
        Ok(Err(ServiceError::Unavailable(_))) => Err(demo_json(
            StatusCode::SERVICE_UNAVAILABLE,
            json!({ "error": "memory service temporarily unavailable" }),
        )),
        Ok(Err(ServiceError::Internal(_))) => Err(demo_json(
            StatusCode::INTERNAL_SERVER_ERROR,
            json!({ "error": "memory operation failed" }),
        )),
        Err(_) => Err(demo_json(
            StatusCode::GATEWAY_TIMEOUT,
            json!({ "error": "memory read deadline exceeded" }),
        )),
    }
}

fn with_demo_server_timing(
    mut response: Response,
    started: std::time::Instant,
    metric: &str,
) -> Response {
    let duration_ms = started.elapsed().as_secs_f64() * 1_000.0;
    if let Ok(value) = HeaderValue::from_str(&format!("{metric};dur={duration_ms:.1}")) {
        response.headers_mut().insert("server-timing", value);
    }
    response
}

fn demo_too_many_requests(message: &str, retry_after: Duration) -> Response {
    let mut response = demo_json(StatusCode::TOO_MANY_REQUESTS, json!({ "error": message }));
    let rounded_seconds = retry_after
        .as_secs()
        .saturating_add(u64::from(retry_after.subsec_nanos() > 0))
        .max(1);
    if let Ok(value) = HeaderValue::from_str(&rounded_seconds.to_string()) {
        response.headers_mut().insert(header::RETRY_AFTER, value);
    }
    response
}

fn bounded_demo_response(result: RecallResult) -> Response {
    bounded_demo_value(result).map_or_else(demo_response_too_large, |value| {
        demo_json(StatusCode::OK, value)
    })
}

fn bounded_demo_value(mut result: RecallResult) -> Option<Value> {
    const MAX_TEXT_CHARS: usize = 2_000;
    if let Some(hits) = result.data.get_mut("hits").and_then(Value::as_array_mut) {
        for hit in hits {
            for key in ["text", "snippet"] {
                let truncated = hit
                    .get(key)
                    .and_then(Value::as_str)
                    .filter(|text| text.chars().count() > MAX_TEXT_CHARS)
                    .map(|text| {
                        format!("{}…", text.chars().take(MAX_TEXT_CHARS).collect::<String>())
                    });
                if let Some(truncated) = truncated {
                    hit[key] = Value::String(truncated);
                }
            }
        }
    }
    let value = json!({
        "data": result.data,
        "conflicts": result.conflicts,
        "conflict_coverage": result.conflict_coverage,
        "warnings": result.warnings,
        "diagnostics": result.diagnostics,
    });
    if serde_json::to_vec(&value).is_ok_and(|bytes| bytes.len() <= MAX_DEMO_RESPONSE_BYTES) {
        Some(value)
    } else {
        tracing::warn!("bounded demo response exceeded output budget");
        None
    }
}

fn demo_response_too_large() -> Response {
    demo_json(
        StatusCode::PAYLOAD_TOO_LARGE,
        json!({ "error": "result is too large; narrow the query or lower its limit" }),
    )
}

fn demo_json(status: StatusCode, value: Value) -> Response {
    let mut response = (status, Json(value)).into_response();
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-store"));
    response.headers_mut().insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    response
}

async fn run_ingest(config: &FleetConfig, input: &str) -> anyhow::Result<()> {
    let model_identity = config.embedding_model_identity();
    let chunks = read_input(input, &config.default_scope, &model_identity)?;
    let embedder = load_pinned_embedder(config)?;
    let store = connect_store(config).await?;
    store.health_check().await?;
    store.initialize_embedding_model(&model_identity).await?;

    let rows = embed_chunks(&chunks, &config.default_scope, &model_identity, &embedder)?;
    let count = rows.len();
    for row in &rows {
        store.upsert_chunk(row).await?;
    }

    println!(
        "{}",
        serde_json::to_string_pretty(&json!({
            "upserted": count,
            "tenant_id": config.default_scope.tenant_id,
            "project": config.default_scope.project,
            "embedding_model": model_identity,
        }))?
    );
    Ok(())
}

fn load_pinned_embedder(config: &FleetConfig) -> anyhow::Result<PinnedEmbedder> {
    let canonical_before = config.verify_embedding_model_bundle()?;
    let local_path = canonical_before.to_str().ok_or_else(|| {
        anyhow::anyhow!("embedding model bundle path must be valid UTF-8 for model2vec")
    })?;
    let inner = Embedder::load(local_path).context("load verified local embedding model bundle")?;
    let canonical_after = config.verify_embedding_model_bundle()?;
    ensure!(
        canonical_before == canonical_after,
        "embedding model bundle path changed while the model was loading"
    );
    ensure!(
        inner.dim() == EMBEDDING_DIMENSION,
        "embedding model dimension mismatch: schema requires {EMBEDDING_DIMENSION}, bundle produced {}",
        inner.dim()
    );
    Ok(PinnedEmbedder {
        inner,
        identity: config.embedding_model_identity(),
    })
}

fn read_input(input: &str, scope: &FleetScope, model_identity: &str) -> anyhow::Result<Vec<Chunk>> {
    if input == "-" {
        let stdin = io::stdin();
        return read_ndjson(stdin.lock(), scope, model_identity).context("read NDJSON from stdin");
    }

    let path = Path::new(input);
    let file = File::open(path).with_context(|| format!("open NDJSON input {}", path.display()))?;
    ensure!(
        file.metadata()
            .with_context(|| format!("inspect NDJSON input {}", path.display()))?
            .is_file(),
        "NDJSON input {} must be a regular file; use --input - for stdin",
        path.display()
    );
    read_ndjson(BufReader::new(file), scope, model_identity)
        .with_context(|| format!("read NDJSON input {}", path.display()))
}

fn read_ndjson<R: BufRead>(
    mut reader: R,
    scope: &FleetScope,
    model_identity: &str,
) -> anyhow::Result<Vec<Chunk>> {
    let mut chunks = Vec::new();
    let mut chunk_ids = HashSet::new();
    let mut line_number = 0_usize;
    let mut total_bytes = 0_usize;

    loop {
        let mut line = Vec::new();
        let count = (&mut reader)
            .take((MAX_NDJSON_LINE_BYTES + 1) as u64)
            .read_until(b'\n', &mut line)?;
        if count == 0 {
            break;
        }
        line_number += 1;
        ensure!(
            count <= MAX_NDJSON_LINE_BYTES,
            "NDJSON line {line_number} exceeds the {MAX_NDJSON_LINE_BYTES}-byte limit"
        );
        total_bytes = total_bytes
            .checked_add(count)
            .ok_or_else(|| anyhow::anyhow!("NDJSON input size overflow"))?;
        ensure!(
            total_bytes <= MAX_TOTAL_INPUT_BYTES,
            "NDJSON input exceeds the {MAX_TOTAL_INPUT_BYTES}-byte total limit"
        );

        if line.last() == Some(&b'\n') {
            line.pop();
        }
        if line.last() == Some(&b'\r') {
            line.pop();
        }
        if line.iter().all(u8::is_ascii_whitespace) {
            continue;
        }

        ensure!(
            chunks.len() < MAX_INGEST_RECORDS,
            "NDJSON input exceeds the {MAX_INGEST_RECORDS}-record limit"
        );
        let text = std::str::from_utf8(&line)
            .with_context(|| format!("NDJSON line {line_number} is not valid UTF-8"))?;
        let record: IngestRecord = serde_json::from_str(text)
            .with_context(|| format!("invalid NDJSON record at line {line_number}"))?;
        let chunk = build_chunk(record, scope, model_identity)
            .with_context(|| format!("invalid NDJSON record at line {line_number}"))?;
        ensure!(
            chunk_ids.insert(chunk.chunk_id.clone()),
            "duplicate chunk identity at NDJSON line {line_number}"
        );
        chunks.push(chunk);
    }

    ensure!(!chunks.is_empty(), "NDJSON input contains no records");
    Ok(chunks)
}

fn build_chunk(
    mut record: IngestRecord,
    scope: &FleetScope,
    model_identity: &str,
) -> anyhow::Result<Chunk> {
    validate_identifier("source_id", &record.source_id, MAX_SOURCE_ID_BYTES)?;
    validate_identifier(
        "source_config_id",
        &record.source_config_id,
        MAX_SOURCE_CONFIG_ID_BYTES,
    )?;
    ensure!(!record.text.trim().is_empty(), "text must not be blank");
    ensure!(
        record.text.len() <= MAX_TEXT_BYTES,
        "text exceeds the {MAX_TEXT_BYTES}-byte limit"
    );
    ensure!(
        !record.text.contains('\0'),
        "text must not contain NUL bytes"
    );
    validate_tsvector_lexemes(&record.text)?;
    validate_links(&record.links)?;
    validate_facets(&record.facets)?;

    for &reserved in DEPLOYMENT_CONTROLLED_INGEST_KEYS {
        ensure!(
            !record.facets.contains_key(reserved),
            "facet {reserved:?} is deployment-controlled and must be omitted"
        );
    }
    for &reserved in INTERNAL_PROJECTION_INGEST_KEYS {
        ensure!(
            !record.facets.contains_key(reserved),
            "facet {reserved:?} is reserved for Recall internals"
        );
    }
    let extra = record
        .extra
        .as_object()
        .ok_or_else(|| anyhow::anyhow!("extra must be a JSON object"))?;
    for &reserved in DEPLOYMENT_CONTROLLED_INGEST_KEYS
        .iter()
        .chain(INTERNAL_PROJECTION_INGEST_KEYS)
    {
        ensure!(
            !extra.contains_key(reserved),
            "extra field {reserved:?} is reserved for Recall internals"
        );
    }

    record
        .facets
        .insert("project".into(), BTreeSet::from([scope.project.clone()]));
    record
        .facets
        .insert("agent".into(), BTreeSet::from([scope.agent.clone()]));
    validate_facets(&record.facets)?;

    let chunk_id = Chunk::make_id(
        record.source,
        &record.source_id,
        record.chunk_index,
        &record.source_config_id,
    );
    let sha256 = Chunk::content_hash(&record.text);
    let header = compose_header(&filter_to_allowlist(&record.facets));
    let embedding_input_sha256 = Chunk::embedding_input_hash(model_identity, &header, &record.text);
    let chunk = Chunk {
        chunk_id,
        source: record.source,
        project: Some(scope.project.clone()),
        source_id: record.source_id,
        source_config_id: record.source_config_id,
        chunk_index: record.chunk_index,
        ts: record.ts,
        role: record.role.map(|role| role.as_str().to_owned()),
        text: record.text,
        sha256,
        links: record.links,
        facets: record.facets,
        embedding_input_sha256,
        extra: record.extra,
    };
    ensure!(
        !is_archive_parent(&chunk),
        "archive-parent chunks are not accepted by active corpus ingestion"
    );
    Ok(chunk)
}

fn validate_tsvector_lexemes(text: &str) -> anyhow::Result<()> {
    for lexeme in text.split_whitespace() {
        let bytes = lexeme.len();
        ensure!(
            bytes <= MAX_TSVECTOR_INPUT_LEXEME_BYTES,
            "text contains a whitespace-delimited lexeme of {bytes} UTF-8 bytes; \
             the ingest limit is {MAX_TSVECTOR_INPUT_LEXEME_BYTES} bytes to remain below \
             CockroachDB's {COCKROACH_TSVECTOR_LEXEME_BYTES}-byte TSVECTOR lexeme limit"
        );
    }
    Ok(())
}

fn validate_identifier(label: &str, value: &str, max_bytes: usize) -> anyhow::Result<()> {
    ensure!(!value.is_empty(), "{label} must not be empty");
    ensure!(
        value == value.trim(),
        "{label} must not have leading or trailing whitespace"
    );
    ensure!(
        value.len() <= max_bytes,
        "{label} exceeds the {max_bytes}-byte limit"
    );
    ensure!(
        !value.chars().any(char::is_control),
        "{label} must not contain control characters"
    );
    Ok(())
}

fn validate_links(links: &Links) -> anyhow::Result<()> {
    if let Some(value) = &links.duckdb_row_key {
        validate_identifier("links.duckdb_row_key", value, MAX_LINK_ID_BYTES)?;
    }
    if let Some(value) = &links.file_path {
        validate_identifier("links.file_path", value, MAX_LINK_ID_BYTES)?;
    }
    ensure!(
        links.parent_ids.len() <= MAX_PARENT_LINKS,
        "links.parent_ids exceeds the {MAX_PARENT_LINKS}-entry limit"
    );
    for parent_id in &links.parent_ids {
        validate_identifier("links.parent_ids entry", parent_id, MAX_LINK_ID_BYTES)?;
    }
    Ok(())
}

fn validate_facets(facets: &FacetSet) -> anyhow::Result<()> {
    ensure!(
        facets.len() <= MAX_FACET_KEYS,
        "facets exceeds the {MAX_FACET_KEYS}-key limit"
    );
    for (key, values) in facets {
        ensure!(
            key.len() <= MAX_FACET_KEY_BYTES && is_valid_facet_key(key),
            "invalid facet key {key:?}"
        );
        ensure!(!values.is_empty(), "facet {key:?} has no values");
        ensure!(
            values.len() <= MAX_FACET_VALUES_PER_KEY,
            "facet {key:?} exceeds the {MAX_FACET_VALUES_PER_KEY}-value limit"
        );
        for value in values {
            ensure!(!value.is_empty(), "facet {key:?} contains an empty value");
            ensure!(
                value == value.trim(),
                "facet {key:?} values must not have surrounding whitespace"
            );
            ensure!(
                value.len() <= MAX_FACET_VALUE_BYTES,
                "facet {key:?} value exceeds the {MAX_FACET_VALUE_BYTES}-byte limit"
            );
            ensure!(
                !value.chars().any(char::is_control),
                "facet {key:?} values must not contain control characters"
            );
        }
    }
    Ok(())
}

fn embed_chunks(
    chunks: &[Chunk],
    scope: &FleetScope,
    model_identity: &str,
    embedder: &PinnedEmbedder,
) -> anyhow::Result<Vec<ScopedChunk>> {
    let mut rows = Vec::with_capacity(chunks.len());
    for batch in chunks.chunks(EMBED_BATCH_SIZE) {
        let texts = batch
            .iter()
            .map(|chunk| chunk.text.as_str())
            .collect::<Vec<_>>();
        let embeddings = embedder.encode_batch(&texts);
        ensure!(
            embeddings.len() == batch.len(),
            "embedder returned {} vectors for {} chunks",
            embeddings.len(),
            batch.len()
        );
        for (chunk, embedding) in batch.iter().cloned().zip(embeddings) {
            validate_embedding(&embedding)?;
            rows.push(ScopedChunk {
                scope: scope.clone(),
                chunk,
                embedding_model: model_identity.to_owned(),
                embedding,
                stale: false,
            });
        }
    }
    Ok(rows)
}

fn validate_embedding(embedding: &[f32]) -> anyhow::Result<()> {
    ensure!(
        embedding.len() == EMBEDDING_DIMENSION,
        "embedding dimension mismatch: expected {EMBEDDING_DIMENSION}, got {}",
        embedding.len()
    );
    ensure!(
        embedding.iter().all(|component| component.is_finite()),
        "embedding contains a non-finite component"
    );
    let norm_squared = embedding
        .iter()
        .map(|component| f64::from(*component).powi(2))
        .sum::<f64>();
    ensure!(norm_squared > 0.0, "embedding has zero norm");
    Ok(())
}

fn default_source_config_id() -> String {
    DEFAULT_SOURCE_CONFIG_ID.into()
}

fn empty_object() -> Value {
    Value::Object(Map::new())
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::io::Cursor;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::{Arc, Mutex};

    use axum::body::{Body, to_bytes};
    use axum::http::Request;
    use ostk_fleet_recall::service::{RememberRequest, RememberResult, ServiceResult};
    use ostk_recall_core::PrivacyTier;
    use tower::ServiceExt as _;
    use uuid::Uuid;

    use super::*;

    fn scope() -> FleetScope {
        FleetScope::new(
            Uuid::parse_str("0198a849-f6ae-7d61-9800-000000000001").expect("uuid"),
            "trusted-project",
            "trusted-agent",
            None,
            PrivacyTier::T1Project,
        )
        .expect("scope")
    }

    #[derive(Default)]
    struct DemoService {
        queries: Mutex<Vec<String>>,
        status_calls: AtomicUsize,
        status_failures_remaining: AtomicUsize,
        status_payload: Mutex<Option<Value>>,
        status_block: Mutex<Option<Arc<tokio::sync::Semaphore>>>,
    }

    #[async_trait]
    impl FleetMemoryService for DemoService {
        async fn recall(
            &self,
            _scope: FleetScope,
            request: RecallRequest,
        ) -> ServiceResult<RecallResult> {
            if request.action == RecallAction::Status {
                self.status_calls.fetch_add(1, Ordering::SeqCst);
                let block = self.status_block.lock().unwrap().clone();
                if let Some(block) = block
                    && block.acquire().await.is_err()
                {
                    return Err(ServiceError::Unavailable(
                        "injected status blocker closed".into(),
                    ));
                }
                if self
                    .status_failures_remaining
                    .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |remaining| {
                        remaining.checked_sub(1)
                    })
                    .is_ok()
                {
                    return Err(ServiceError::Unavailable("injected status failure".into()));
                }
                let value = self
                    .status_payload
                    .lock()
                    .unwrap()
                    .clone()
                    .unwrap_or_else(|| json!({ "status": "ready" }));
                return Ok(RecallResult::new(value));
            }
            let query = request
                .arguments
                .get("query")
                .and_then(Value::as_str)
                .expect("demo query")
                .to_owned();
            assert_eq!(request.arguments.get("max_per_source_id"), Some(&json!(1)));
            self.queries.lock().unwrap().push(query);
            Ok(RecallResult::new(json!({
                "hits": [{
                    "chunk_id": "demo-1",
                    "text": "CockroachDB is the durable shared memory plane.",
                    "score": 0.97
                }]
            })))
        }

        async fn remember(
            &self,
            _scope: FleetScope,
            _request: RememberRequest,
        ) -> ServiceResult<RememberResult> {
            panic!("the public demo router must never expose remember")
        }
    }

    struct ReadyHealth;

    #[async_trait]
    impl DemoHealth for ReadyHealth {
        async fn ready(&self) -> Result<(), ()> {
            Ok(())
        }
    }

    struct BlockingHealth {
        entered: AtomicUsize,
        release: tokio::sync::Semaphore,
        succeed: bool,
    }

    #[async_trait]
    impl DemoHealth for BlockingHealth {
        async fn ready(&self) -> Result<(), ()> {
            self.entered.fetch_add(1, Ordering::SeqCst);
            let _permit = self.release.acquire().await.map_err(|_| ())?;
            if self.succeed { Ok(()) } else { Err(()) }
        }
    }

    #[derive(Default)]
    struct CountingHealth {
        calls: AtomicUsize,
        failures_remaining: AtomicUsize,
    }

    #[async_trait]
    impl DemoHealth for CountingHealth {
        async fn ready(&self) -> Result<(), ()> {
            self.calls.fetch_add(1, Ordering::SeqCst);
            if self
                .failures_remaining
                .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |remaining| {
                    remaining.checked_sub(1)
                })
                .is_ok()
            {
                Err(())
            } else {
                Ok(())
            }
        }
    }

    struct ManualDemoClock {
        now: Mutex<tokio::time::Instant>,
    }

    impl ManualDemoClock {
        fn new() -> Self {
            Self {
                now: Mutex::new(tokio::time::Instant::now()),
            }
        }

        fn advance(&self, duration: Duration) {
            let mut now = self.now.lock().unwrap();
            *now = now.checked_add(duration).expect("test clock overflow");
        }
    }

    impl DemoClock for ManualDemoClock {
        fn now(&self) -> tokio::time::Instant {
            *self.now.lock().unwrap()
        }
    }

    fn test_rate_policy(burst: u32) -> DemoRatePolicy {
        DemoRatePolicy {
            burst,
            refill_interval: Duration::from_millis(1),
        }
    }

    fn controlled_demo_state(
        service: Arc<dyn FleetMemoryService>,
        clock: Arc<ManualDemoClock>,
        status_policy: DemoRatePolicy,
        recall_policy: DemoRatePolicy,
        status_cache_ttl: Duration,
    ) -> DemoState {
        let now = clock.now();
        let clock: Arc<dyn DemoClock> = clock;
        DemoState {
            service,
            health: Arc::new(ReadyHealth),
            scope: scope(),
            capacity: Arc::new(tokio::sync::Semaphore::new(2)),
            health_capacity: Arc::new(tokio::sync::Semaphore::new(2)),
            rate_limits: Arc::new(DemoRateLimits::with_policies(
                now,
                status_policy,
                recall_policy,
            )),
            health_cache: Arc::new(DemoHealthCache::new(DEMO_HEALTH_CACHE_TTL)),
            status_cache: Arc::new(DemoStatusCache::new(status_cache_ttl)),
            clock,
        }
    }

    fn controlled_demo_router(
        service: Arc<dyn FleetMemoryService>,
        clock: Arc<ManualDemoClock>,
        status_policy: DemoRatePolicy,
        recall_policy: DemoRatePolicy,
        status_cache_ttl: Duration,
    ) -> Router {
        demo_router(controlled_demo_state(
            service,
            clock,
            status_policy,
            recall_policy,
            status_cache_ttl,
        ))
    }

    fn test_demo_router(service: Arc<DemoService>) -> Router {
        controlled_demo_router(
            service,
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(100),
            test_rate_policy(100),
            DEMO_STATUS_CACHE_TTL,
        )
    }

    async fn assert_demo_error(
        response: Response,
        expected_status: StatusCode,
        expected_message: &str,
    ) {
        assert_eq!(response.status(), expected_status);
        assert_eq!(response.headers()[header::CACHE_CONTROL], "no-store");
        assert_eq!(response.headers()[header::CONTENT_TYPE], "application/json");
        let body = to_bytes(response.into_body(), 1_024)
            .await
            .expect("demo error must be bounded");
        let value: Value = serde_json::from_slice(&body).expect("demo error must be JSON");
        assert_eq!(value, json!({ "error": expected_message }));
    }

    async fn demo_status_request(router: &Router) -> Response {
        router
            .clone()
            .oneshot(Request::get("/api/status").body(Body::empty()).unwrap())
            .await
            .unwrap()
    }

    async fn demo_health_request(router: &Router) -> Response {
        router
            .clone()
            .oneshot(Request::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap()
    }

    async fn demo_recall_request(router: &Router, query: &str) -> Response {
        router
            .clone()
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        serde_json::to_vec(&json!({ "query": query, "limit": 8 })).unwrap(),
                    ))
                    .unwrap(),
            )
            .await
            .unwrap()
    }

    fn demo_server_timing(response: &Response) -> &str {
        response
            .headers()
            .get("server-timing")
            .and_then(|value| value.to_str().ok())
            .expect("demo service response must expose server timing")
    }

    #[test]
    fn ingest_cli_defaults_to_stdin() {
        let cli = Cli::try_parse_from(["ostk-fleet-recall", "ingest"]).expect("CLI");
        assert!(matches!(
            cli.command,
            Command::Ingest { ref input } if input == "-"
        ));
    }

    #[test]
    fn demo_cli_contract_matches_ecs_task() {
        let cli = Cli::try_parse_from(["ostk-fleet-recall", "demo", "--listen", "0.0.0.0:8080"])
            .expect("CLI");
        assert!(matches!(
            cli.command,
            Command::Demo { listen } if listen == "0.0.0.0:8080".parse().unwrap()
        ));
    }

    #[test]
    fn reference_agent_cli_contract_matches_ecs_overrides() {
        let cli = Cli::try_parse_from([
            "ostk-fleet-recall",
            "reference-agent",
            "--step",
            "recall-and-act",
            "--run-id",
            "cloud-proof-1",
        ])
        .expect("CLI");
        assert!(matches!(
            cli.command,
            Command::ReferenceAgent {
                step: ReferenceAgentStep::RecallAndAct,
                ref run_id,
            } if run_id == "cloud-proof-1"
        ));
    }

    #[test]
    fn migration_preflight_rejects_hash_valid_but_malformed_model_bundle() {
        let bundle = tempfile::tempdir().expect("tempdir");
        fs::write(bundle.path().join("config.json"), b"not model2vec config").expect("config");
        fs::write(bundle.path().join("model.safetensors"), b"not safetensors").expect("weights");
        fs::write(bundle.path().join("tokenizer.json"), b"not a tokenizer").expect("tokenizer");
        let digest = model_bundle_sha256(bundle.path()).expect("hash-valid bundle");
        let config = FleetConfig {
            database_url: "postgresql://example.invalid/defaultdb".into(),
            default_scope: scope(),
            max_connections: 1,
            embedding_model: "logical/model".into(),
            embedding_model_path: bundle.path().into(),
            embedding_model_sha256: digest,
        };

        assert!(
            config.verify_embedding_model_bundle().is_ok(),
            "fixture must pass byte-integrity verification"
        );
        let error = validated_migration_model_identity(&config)
            .expect_err("malformed bundle must fail before registry initialization");
        assert!(
            error
                .to_string()
                .contains("load verified local embedding model bundle")
        );
    }

    #[tokio::test]
    async fn demo_router_is_ready_and_read_only() {
        let service = Arc::new(DemoService::default());
        let router = test_demo_router(service.clone());

        let health = router
            .clone()
            .oneshot(Request::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(health.status(), StatusCode::OK);

        let response = router
            .clone()
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"query":"Why CockroachDB?","limit":8}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(response.headers()[header::CACHE_CONTROL], "no-store");
        let server_timing = response
            .headers()
            .get("server-timing")
            .and_then(|value| value.to_str().ok())
            .expect("recall response must expose server timing");
        let duration = server_timing
            .strip_prefix("fleet-recall;dur=")
            .and_then(|value| value.parse::<f64>().ok())
            .expect("server timing must use a numeric duration");
        assert!(duration >= 0.0);
        let body = to_bytes(response.into_body(), MAX_DEMO_RESPONSE_BYTES)
            .await
            .unwrap();
        let value: Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(value["data"]["hits"][0]["chunk_id"], "demo-1");
        assert_eq!(
            service.queries.lock().unwrap().as_slice(),
            ["Why CockroachDB?"]
        );

        let mutation = router
            .oneshot(
                Request::post("/api/remember")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"text":"must not run"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(mutation.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn demo_route_rate_limits_bound_bursts_refill_and_remain_isolated() {
        let service = Arc::new(DemoService::default());
        let clock = Arc::new(ManualDemoClock::new());
        let router = controlled_demo_router(
            service.clone(),
            clock.clone(),
            DemoRatePolicy {
                burst: 1,
                refill_interval: Duration::from_millis(500),
            },
            DemoRatePolicy {
                burst: 2,
                refill_interval: Duration::from_secs(1),
            },
            DEMO_STATUS_CACHE_TTL,
        );

        assert_eq!(
            demo_recall_request(&router, "first").await.status(),
            StatusCode::OK
        );
        assert_eq!(
            demo_recall_request(&router, "second").await.status(),
            StatusCode::OK
        );
        let limited_recall = demo_recall_request(&router, "limited").await;
        assert_eq!(limited_recall.headers()[header::RETRY_AFTER], "1");
        assert_demo_error(
            limited_recall,
            StatusCode::TOO_MANY_REQUESTS,
            "request rate limit exceeded; retry shortly",
        )
        .await;
        assert_eq!(service.queries.lock().unwrap().len(), 2);
        let malformed_while_limited = router
            .clone()
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"query":"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_demo_error(
            malformed_while_limited,
            StatusCode::TOO_MANY_REQUESTS,
            "request rate limit exceeded; retry shortly",
        )
        .await;

        // The status policy is independent from the exhausted recall bucket.
        assert_eq!(demo_status_request(&router).await.status(), StatusCode::OK);
        let limited_status = demo_status_request(&router).await;
        assert_eq!(limited_status.headers()[header::RETRY_AFTER], "1");
        assert_demo_error(
            limited_status,
            StatusCode::TOO_MANY_REQUESTS,
            "request rate limit exceeded; retry shortly",
        )
        .await;
        let health = router
            .clone()
            .oneshot(Request::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(health.status(), StatusCode::OK);

        clock.advance(Duration::from_millis(500));
        let refilled_status = demo_status_request(&router).await;
        assert_eq!(refilled_status.status(), StatusCode::OK);
        assert!(demo_server_timing(&refilled_status).starts_with("fleet-recall-cache;dur="));
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 1);

        let still_limited_recall = demo_recall_request(&router, "still limited").await;
        assert_eq!(still_limited_recall.status(), StatusCode::TOO_MANY_REQUESTS);
        clock.advance(Duration::from_millis(500));
        assert_eq!(
            demo_recall_request(&router, "refilled").await.status(),
            StatusCode::OK
        );
        assert_eq!(service.queries.lock().unwrap().len(), 3);
    }

    #[tokio::test]
    async fn demo_capacity_limit_also_returns_a_bounded_retry_after() {
        let service = Arc::new(DemoService::default());
        let state = controlled_demo_state(
            service.clone(),
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(10),
            test_rate_policy(10),
            DEMO_STATUS_CACHE_TTL,
        );
        let held = state
            .capacity
            .clone()
            .try_acquire_many_owned(2)
            .expect("hold all test API capacity");
        let router = demo_router(state);

        let response = demo_recall_request(&router, "bounded capacity").await;
        assert_eq!(response.headers()[header::RETRY_AFTER], "1");
        assert!(demo_server_timing(&response).starts_with("fleet-recall;dur="));
        assert_demo_error(
            response,
            StatusCode::TOO_MANY_REQUESTS,
            "demo is busy; retry shortly",
        )
        .await;
        assert!(service.queries.lock().unwrap().is_empty());
        drop(held);
    }

    #[tokio::test]
    async fn demo_status_cache_serves_concurrent_hits_without_backend_work() {
        let service = Arc::new(DemoService::default());
        let router = controlled_demo_router(
            service.clone(),
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(16),
            test_rate_policy(16),
            DEMO_STATUS_CACHE_TTL,
        );
        let responses =
            futures::future::join_all((0..8).map(|_| demo_status_request(&router))).await;

        assert_eq!(service.status_calls.load(Ordering::SeqCst), 1);
        let mut cache_hits = 0;
        let mut cache_misses = 0;
        for response in responses {
            assert_eq!(response.status(), StatusCode::OK);
            let timing = demo_server_timing(&response);
            if timing.starts_with("fleet-recall-cache;dur=") {
                cache_hits += 1;
            } else {
                assert!(timing.starts_with("fleet-recall;dur="));
                cache_misses += 1;
            }
            let body = to_bytes(response.into_body(), MAX_DEMO_RESPONSE_BYTES)
                .await
                .expect("cached status response must remain bounded");
            assert!(body.len() <= MAX_DEMO_RESPONSE_BYTES);
        }
        assert_eq!(cache_misses, 1);
        assert_eq!(cache_hits, 7);
    }

    #[tokio::test]
    async fn demo_status_slow_failure_rejects_concurrent_misses_without_fanout() {
        let block = Arc::new(tokio::sync::Semaphore::new(0));
        let service = Arc::new(DemoService {
            status_failures_remaining: AtomicUsize::new(1),
            status_block: Mutex::new(Some(block.clone())),
            ..DemoService::default()
        });
        let router = controlled_demo_router(
            service.clone(),
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(10),
            test_rate_policy(10),
            DEMO_STATUS_CACHE_TTL,
        );
        let first = tokio::spawn({
            let router = router.clone();
            async move { demo_status_request(&router).await }
        });
        tokio::time::timeout(Duration::from_secs(1), async {
            while service.status_calls.load(Ordering::SeqCst) < 1 {
                tokio::task::yield_now().await;
            }
        })
        .await
        .expect("one status refresh must enter the service");

        for _ in 0..2 {
            let rejected =
                tokio::time::timeout(Duration::from_millis(100), demo_status_request(&router))
                    .await
                    .expect("concurrent status misses must fail without waiting");
            assert_eq!(rejected.headers()[header::RETRY_AFTER], "1");
            assert!(demo_server_timing(&rejected).starts_with("fleet-recall-overload;dur="));
            assert_demo_error(
                rejected,
                StatusCode::TOO_MANY_REQUESTS,
                "status refresh is in progress; retry shortly",
            )
            .await;
        }
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 1);

        block.add_permits(1);
        let failed = first.await.unwrap();
        assert_eq!(failed.status(), StatusCode::SERVICE_UNAVAILABLE);
        assert!(demo_server_timing(&failed).starts_with("fleet-recall;dur="));
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 1);

        let recovered = demo_status_request(&router).await;
        assert_eq!(recovered.status(), StatusCode::OK);
        assert!(demo_server_timing(&recovered).starts_with("fleet-recall;dur="));
        assert_eq!(demo_status_request(&router).await.status(), StatusCode::OK);
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn demo_status_cache_expires_on_the_manual_clock() {
        let service = Arc::new(DemoService::default());
        let clock = Arc::new(ManualDemoClock::new());
        let ttl = Duration::from_secs(2);
        let router = controlled_demo_router(
            service.clone(),
            clock.clone(),
            test_rate_policy(10),
            test_rate_policy(10),
            ttl,
        );

        let first = demo_status_request(&router).await;
        assert!(demo_server_timing(&first).starts_with("fleet-recall;dur="));
        clock.advance(
            ttl.checked_sub(Duration::from_millis(1))
                .expect("test status-cache TTL exceeds one millisecond"),
        );
        let hit = demo_status_request(&router).await;
        assert!(demo_server_timing(&hit).starts_with("fleet-recall-cache;dur="));
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 1);

        clock.advance(Duration::from_millis(1));
        let expired = demo_status_request(&router).await;
        assert!(demo_server_timing(&expired).starts_with("fleet-recall;dur="));
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn demo_status_failures_are_never_cached() {
        let service = Arc::new(DemoService {
            status_failures_remaining: AtomicUsize::new(1),
            ..DemoService::default()
        });
        let router = test_demo_router(service.clone());

        let failure = demo_status_request(&router).await;
        assert!(demo_server_timing(&failure).starts_with("fleet-recall;dur="));
        assert_demo_error(
            failure,
            StatusCode::SERVICE_UNAVAILABLE,
            "memory service temporarily unavailable",
        )
        .await;
        let recovered = demo_status_request(&router).await;
        assert_eq!(recovered.status(), StatusCode::OK);
        assert!(demo_server_timing(&recovered).starts_with("fleet-recall;dur="));
        let cached = demo_status_request(&router).await;
        assert_eq!(cached.status(), StatusCode::OK);
        assert!(demo_server_timing(&cached).starts_with("fleet-recall-cache;dur="));
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn oversized_status_responses_remain_bounded_and_are_not_cached() {
        let service = Arc::new(DemoService {
            status_payload: Mutex::new(Some(json!({
                "status": "ready",
                "oversized": "x".repeat(MAX_DEMO_RESPONSE_BYTES),
            }))),
            ..DemoService::default()
        });
        let router = test_demo_router(service.clone());

        for _ in 0..2 {
            let response = demo_status_request(&router).await;
            assert!(demo_server_timing(&response).starts_with("fleet-recall;dur="));
            assert_demo_error(
                response,
                StatusCode::PAYLOAD_TOO_LARGE,
                "result is too large; narrow the query or lower its limit",
            )
            .await;
        }
        assert_eq!(service.status_calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn demo_page_leads_with_conflict_story_and_keeps_raw_evidence_collapsed() {
        let router = test_demo_router(Arc::new(DemoService::default()));
        let response = router
            .oneshot(Request::get("/").body(Body::empty()).unwrap())
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
        assert!(
            response
                .headers()
                .get(header::CONTENT_SECURITY_POLICY)
                .is_some()
        );
        let body = to_bytes(response.into_body(), 128 * 1024).await.unwrap();
        let page = std::str::from_utf8(&body).expect("demo page must be UTF-8");
        assert!(page.contains("When agents disagree, memory should"));
        assert!(page.contains("Does MCP remember support deliberate retractions?"));
        assert!(
            page.contains("How are conflicting migration strategies represented and escalated?")
        );
        assert!(page.contains("incompatible typed claims"));
        assert!(page.contains("claim_support_chunk_index_enabled"));
        assert!(page.contains("conflict_matches"));
        assert!(page.contains("source_support"));
        assert!(page.contains("fused_hit_rank"));
        assert!(page.contains("<details id=\"raw\" hidden>"));
        assert!(page.contains("View raw evidence envelope"));
        assert!(page.contains("response.headers.get('server-timing')"));
        assert!(page.contains("document.createElement(tag)"));
        assert!(page.contains("Verified on AWS"));
        assert!(page.contains("syncSampleSelection"));
        assert!(page.contains("aria-pressed=\"true\""));
        assert!(page.contains("exact retrieved claim/source association"));
        assert!(page.contains("rich-demo/docs/"));
        assert!(page.contains("src\\/[A-Za-z0-9._/-]+\\.rs"));
        assert!(page.contains("https://github.com/os-tack/ostk-fleet-recall/blob/main/"));
        assert!(!page.contains("innerHTML"));
    }

    #[tokio::test]
    async fn demo_health_singleflights_without_competing_with_recall_capacity() {
        let service = Arc::new(DemoService::default());
        let capacity = Arc::new(tokio::sync::Semaphore::new(1));
        let held_recall = capacity.clone().try_acquire_owned().unwrap();
        let health_capacity = Arc::new(tokio::sync::Semaphore::new(2));
        let health = Arc::new(BlockingHealth {
            entered: AtomicUsize::new(0),
            release: tokio::sync::Semaphore::new(0),
            succeed: true,
        });
        let defaults = controlled_demo_state(
            service,
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(100),
            test_rate_policy(100),
            DEMO_STATUS_CACHE_TTL,
        );
        let router = demo_router(DemoState {
            health: health.clone(),
            capacity,
            health_capacity,
            ..defaults
        });

        let first_router = router.clone();
        let first = tokio::spawn(async move {
            first_router
                .oneshot(Request::get("/healthz").body(Body::empty()).unwrap())
                .await
                .unwrap()
        });
        tokio::time::timeout(Duration::from_secs(1), async {
            while health.entered.load(Ordering::SeqCst) < 1 {
                tokio::task::yield_now().await;
            }
        })
        .await
        .expect("one readiness probe must enter the backend");
        let second = demo_health_request(&router).await;
        let third = demo_health_request(&router).await;
        assert_eq!(second.status(), StatusCode::SERVICE_UNAVAILABLE);
        assert_eq!(third.status(), StatusCode::SERVICE_UNAVAILABLE);
        assert_eq!(health.entered.load(Ordering::SeqCst), 1);

        health.release.add_permits(1);
        assert_eq!(first.await.unwrap().status(), StatusCode::OK);
        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        assert_eq!(health.entered.load(Ordering::SeqCst), 1);
        drop(held_recall);
    }

    #[tokio::test]
    async fn demo_health_slow_failures_reject_concurrent_misses_without_fanout() {
        let service = Arc::new(DemoService::default());
        let health = Arc::new(BlockingHealth {
            entered: AtomicUsize::new(0),
            release: tokio::sync::Semaphore::new(0),
            succeed: false,
        });
        let defaults = controlled_demo_state(
            service,
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(10),
            test_rate_policy(10),
            DEMO_STATUS_CACHE_TTL,
        );
        let router = demo_router(DemoState {
            health: health.clone(),
            ..defaults
        });
        let first = tokio::spawn({
            let router = router.clone();
            async move { demo_health_request(&router).await }
        });
        tokio::time::timeout(Duration::from_secs(1), async {
            while health.entered.load(Ordering::SeqCst) < 1 {
                tokio::task::yield_now().await;
            }
        })
        .await
        .expect("one health refresh must enter the backend");

        for _ in 0..2 {
            let rejected =
                tokio::time::timeout(Duration::from_millis(100), demo_health_request(&router))
                    .await
                    .expect("concurrent health misses must fail without waiting");
            assert_eq!(rejected.status(), StatusCode::SERVICE_UNAVAILABLE);
            let body = to_bytes(rejected.into_body(), 128)
                .await
                .expect("health overload response must be bounded");
            assert_eq!(
                serde_json::from_slice::<Value>(&body).unwrap(),
                json!({
                    "status": "unavailable",
                    "reason": "readiness check in progress",
                })
            );
        }
        assert_eq!(health.entered.load(Ordering::SeqCst), 1);

        health.release.add_permits(1);
        assert_eq!(
            first.await.unwrap().status(),
            StatusCode::SERVICE_UNAVAILABLE
        );
        assert_eq!(health.entered.load(Ordering::SeqCst), 1);

        // The failure was not cached: the next request owns a fresh backend
        // attempt instead of inheriting the prior failure.
        health.release.add_permits(1);
        assert_eq!(
            demo_health_request(&router).await.status(),
            StatusCode::SERVICE_UNAVAILABLE
        );
        assert_eq!(health.entered.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn demo_health_success_cache_expires_on_the_manual_clock() {
        let service = Arc::new(DemoService::default());
        let health = Arc::new(CountingHealth::default());
        let clock = Arc::new(ManualDemoClock::new());
        let defaults = controlled_demo_state(
            service,
            clock.clone(),
            test_rate_policy(10),
            test_rate_policy(10),
            DEMO_STATUS_CACHE_TTL,
        );
        let router = demo_router(DemoState {
            health: health.clone(),
            ..defaults
        });

        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        clock.advance(
            DEMO_HEALTH_CACHE_TTL
                .checked_sub(Duration::from_millis(1))
                .expect("test health-cache TTL exceeds one millisecond"),
        );
        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        assert_eq!(health.calls.load(Ordering::SeqCst), 1);

        clock.advance(Duration::from_millis(1));
        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        assert_eq!(health.calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn demo_health_failures_are_not_cached() {
        let service = Arc::new(DemoService::default());
        let health = Arc::new(CountingHealth {
            failures_remaining: AtomicUsize::new(1),
            ..CountingHealth::default()
        });
        let defaults = controlled_demo_state(
            service,
            Arc::new(ManualDemoClock::new()),
            test_rate_policy(10),
            test_rate_policy(10),
            DEMO_STATUS_CACHE_TTL,
        );
        let router = demo_router(DemoState {
            health: health.clone(),
            ..defaults
        });

        let failed = demo_health_request(&router).await;
        assert_eq!(failed.status(), StatusCode::SERVICE_UNAVAILABLE);
        let failed_body = to_bytes(failed.into_body(), 128)
            .await
            .expect("health failure response must be bounded");
        assert_eq!(
            serde_json::from_slice::<Value>(&failed_body).unwrap(),
            json!({ "status": "unavailable" })
        );
        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        assert_eq!(demo_health_request(&router).await.status(), StatusCode::OK);
        assert_eq!(health.calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn demo_router_rejects_oversized_queries_before_service() {
        let service = Arc::new(DemoService::default());
        let router = test_demo_router(service.clone());
        let body = serde_json::to_vec(&json!({
            "query": "x".repeat(MAX_DEMO_QUERY_BYTES + 1),
            "limit": 8,
        }))
        .unwrap();
        let response = router
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(body))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        assert!(service.queries.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn demo_api_json_rejections_are_bounded_json_without_serde_details() {
        let service = Arc::new(DemoService::default());
        let router = test_demo_router(service.clone());

        let malformed = router
            .clone()
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"query":"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_demo_error(
            malformed,
            StatusCode::BAD_REQUEST,
            "request body must contain valid JSON",
        )
        .await;

        let wrong_shape = router
            .clone()
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"query":17}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_demo_error(
            wrong_shape,
            StatusCode::UNPROCESSABLE_ENTITY,
            "request JSON does not match the expected shape",
        )
        .await;

        let missing_content_type = router
            .clone()
            .oneshot(
                Request::post("/api/recall")
                    .body(Body::from(r#"{"query":"Why CockroachDB?"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_demo_error(
            missing_content_type,
            StatusCode::UNSUPPORTED_MEDIA_TYPE,
            "content-type must be application/json",
        )
        .await;

        let oversized = serde_json::to_vec(&json!({
            "query": "Why CockroachDB?",
            "unknown": "x".repeat(MAX_DEMO_BODY_BYTES),
        }))
        .unwrap();
        let oversized = router
            .oneshot(
                Request::post("/api/recall")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(oversized))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_demo_error(
            oversized,
            StatusCode::PAYLOAD_TOO_LARGE,
            "request body is too large",
        )
        .await;

        assert!(service.queries.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn demo_api_route_and_method_errors_are_json() {
        let service = Arc::new(DemoService::default());
        let router = test_demo_router(service);

        let method = router
            .clone()
            .oneshot(Request::get("/api/recall").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_demo_error(method, StatusCode::METHOD_NOT_ALLOWED, "method not allowed").await;

        let route = router
            .oneshot(
                Request::post("/api/remember")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"text":"must not run"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_demo_error(route, StatusCode::NOT_FOUND, "API route not found").await;
    }

    #[test]
    fn ndjson_derives_identity_and_authority_from_deployment() {
        let input = br#"{"source":"markdown","source_id":"demo/architecture","text":"Fleet memory","facets":{"tags":["demo"]}}
"#;
        let chunks =
            read_ndjson(Cursor::new(input), &scope(), "logical@sha256:abc").expect("valid input");
        let chunk = &chunks[0];

        assert_eq!(chunk.project.as_deref(), Some("trusted-project"));
        assert_eq!(
            chunk.facets.get("project"),
            Some(&BTreeSet::from(["trusted-project".to_owned()]))
        );
        assert_eq!(
            chunk.facets.get("agent"),
            Some(&BTreeSet::from(["trusted-agent".to_owned()]))
        );
        assert_eq!(
            chunk.chunk_id,
            Chunk::make_id(
                Source::Markdown,
                "demo/architecture",
                0,
                DEFAULT_SOURCE_CONFIG_ID
            )
        );
        assert_eq!(chunk.sha256, Chunk::content_hash("Fleet memory"));
        assert!(!chunk.embedding_input_sha256.is_empty());
    }

    #[test]
    fn ndjson_rejects_top_level_authority_fields() {
        for field in ["tenant_id", "project", "agent", "privacy_tier", "scope"] {
            let input = format!(
                "{{\"source\":\"markdown\",\"source_id\":\"demo\",\"text\":\"body\",\"{field}\":\"override\"}}\n"
            );
            let result = read_ndjson(
                Cursor::new(input.as_bytes()),
                &scope(),
                "logical@sha256:abc",
            );
            assert!(result.is_err(), "authority field {field} must be rejected");
        }
    }

    #[test]
    fn ndjson_rejects_authority_facets_and_internal_projection_fields() {
        let authority = br#"{"source":"markdown","source_id":"demo","text":"body","facets":{"project":["other"]}}
"#;
        assert!(read_ndjson(Cursor::new(authority), &scope(), "logical@sha256:abc").is_err());

        for &field in INTERNAL_PROJECTION_INGEST_KEYS {
            let facet = serde_json::to_string(&json!({
                "source": "markdown",
                "source_id": "demo",
                "text": "body",
                "facets": { field: ["spoofed"] },
            }))
            .unwrap();
            let facet_error = read_ndjson(
                Cursor::new(format!("{facet}\n")),
                &scope(),
                "logical@sha256:abc",
            )
            .expect_err("internal projection facet must fail");
            assert!(
                format!("{facet_error:#}").contains(field),
                "error should identify reserved facet {field}"
            );

            let extra = serde_json::to_string(&json!({
                "source": "markdown",
                "source_id": "demo",
                "text": "body",
                "extra": { field: "spoofed" },
            }))
            .unwrap();
            let extra_error = read_ndjson(
                Cursor::new(format!("{extra}\n")),
                &scope(),
                "logical@sha256:abc",
            )
            .expect_err("internal projection extra field must fail");
            assert!(
                format!("{extra_error:#}").contains(field),
                "error should identify reserved extra field {field}"
            );
        }
    }

    #[test]
    fn tsvector_lexeme_limit_counts_utf8_bytes_at_boundary() {
        let ascii_boundary = "a".repeat(MAX_TSVECTOR_INPUT_LEXEME_BYTES);
        assert!(validate_tsvector_lexemes(&ascii_boundary).is_ok());

        let ascii_over = format!("{ascii_boundary}a");
        let error = validate_tsvector_lexemes(&ascii_over)
            .expect_err("one byte over the conservative boundary must fail");
        let message = error.to_string();
        assert!(message.contains("16001 UTF-8 bytes"));
        assert!(message.contains("16383-byte TSVECTOR lexeme limit"));

        let unicode_boundary = "é".repeat(MAX_TSVECTOR_INPUT_LEXEME_BYTES / 2);
        assert_eq!(unicode_boundary.len(), MAX_TSVECTOR_INPUT_LEXEME_BYTES);
        assert!(validate_tsvector_lexemes(&format!("before {unicode_boundary} after")).is_ok());

        let unicode_over = format!("{unicode_boundary}é");
        assert_eq!(unicode_over.len(), MAX_TSVECTOR_INPUT_LEXEME_BYTES + 2);
        let error = validate_tsvector_lexemes(&unicode_over)
            .expect_err("Unicode lexemes must be bounded by bytes, not scalar count");
        assert!(error.to_string().contains("16002 UTF-8 bytes"));
    }

    #[test]
    fn ndjson_rejects_oversized_tsvector_lexeme_before_ingest() {
        let input = serde_json::to_string(&json!({
            "source": "markdown",
            "source_id": "demo",
            "text": "x".repeat(MAX_TSVECTOR_INPUT_LEXEME_BYTES + 1),
        }))
        .unwrap();
        let error = read_ndjson(
            Cursor::new(format!("{input}\n")),
            &scope(),
            "logical@sha256:abc",
        )
        .expect_err("an oversized TSVECTOR lexeme must fail during NDJSON validation");
        assert!(format!("{error:#}").contains("whitespace-delimited lexeme of 16001 UTF-8 bytes"));
    }

    #[test]
    fn ndjson_rejects_duplicate_stable_identity_before_writes() {
        let input = br#"{"source":"markdown","source_id":"same","text":"first"}
{"source":"markdown","source_id":"same","text":"second"}
"#;
        let error = read_ndjson(Cursor::new(input), &scope(), "logical@sha256:abc")
            .expect_err("duplicate must fail");
        assert!(error.to_string().contains("duplicate chunk identity"));
    }

    #[test]
    fn ndjson_rejects_empty_and_overlong_lines() {
        assert!(read_ndjson(Cursor::new(b"\n"), &scope(), "logical@sha256:abc").is_err());

        let overlong = vec![b'x'; MAX_NDJSON_LINE_BYTES + 1];
        let error = read_ndjson(Cursor::new(overlong), &scope(), "logical@sha256:abc")
            .expect_err("overlong line must fail");
        assert!(error.to_string().contains("exceeds"));
    }
}
